apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-back
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: terezabisharyan/app-backend
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/tereza-arta/back-manifests.git
    targetRevision: main
    path: environments/staging/app
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
